name: pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
        source $HOME/.poetry/env
        poetry config virtualenvs.in-project true
    - name: Install dependencies
      run: |
        source $HOME/.poetry/env
        poetry install
    - name: Test
      run: |
        source $HOME/.poetry/env
        poetry run pytest -q tests
